version: "3.2"
services:

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    volumes:
      - ./14_08_2020.bak:/var/backups/14_08_2020.bak
      - ./BackUp20.08.2020:/var/backups/BackUp20.08.2020
      
  kibana:
    container_name: kibana
    image: kibana:7.9.1
    restart: always
    ports:
      - '5601:5601'
      
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.9.1
    restart: always
    ports:
      - '9200:9200'
    environment:
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node